services:
  backend:
    image: ${{secrets.DOCKER_BACKEND_IMAGE}}
    environment:
      SPRING_DATASOURCE_URL: ${{secrets.SPRING_DATASOURCE_URL}}
      SPRING_DATASOURCE_USERNAME: ${{secrets.SPRING_DATASOURCE_USERNAME}}
      SPRING_DATASOURCE_PASSWORD: ${{secrets.SPRING_DATASOURCE_PASSWORD}}
      SPRING_DATA_REDIS_HOST: ${{secrets.SPRING_DATA_REDIS_HOST}}
      SPRING_DATA_REDIS_PORT: ${{secrets.SPRING_DATA_REDIS_PORT}}
      SPRING_DATA_REDIS_CLIENT_NAME: ${{secrets.SPRING_DATA_REDIS_CLIENT_NAME}}
      SPRING_DATA_REDIS_PASSWORD: ${{secrets.SPRING_DATA_REDIS_PASSWORD}}
    ports:
      - '8080:8080'
    depends_on:
      - mysql
      - redis
    networks:
      - db

  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
      MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - db

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/usr/local/etc/redis
    networks:
      - db

networks:
  db:

volumes:
  mysql_data:
  redis_data: